server:
  port: 8900

zq:
  version: 1.4.1

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.118.1:3306/gzq?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password: gzq102938
      minIdle: 10
      maxActive: 20
      time-between-eviction-runs-millis: 60000
      validation-query: select 1 from dual
  output:
    ansi:
      enabled: detect
  kafka:
    listener:
      ack-mode: manual

    bootstrap-servers: 192.168.118.66:9092
  rabbitmq:
    host: 192.168.118.1
    port: 5672
    username: gzq

    virtual-host: /
    password: gzq102938
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
#  cloud:
#    zookeeper:
#      connect-string: 192.168.118.66:2181
#      discovery:
#        register: true
#        root: /service
#        enabled: true
#  application:
#    name: ol-consumer

dubbo:
  application:
    name: ol-consumer
    logger: slf4j

  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
    timeout: 30000
  protocol:
    port: 28880
    name: dubbo

  consumer:
    loadbalance: roundrobin
    timeout: 30000
    retries: 0

zookeeper:
  address: 192.168.118.66
mybatis:
    mapperLocations: classpath:mapper/**/*Mapper.xml
    configLocation: classpath:mybatis-config.xml

logging:
  level:
    org.yu: debug
    org.springframework: warn
    org.apache.dubbo: warn
    org.apache.zookeeper: warn