server:
  port: 8900

zq:
  version: 1.4.1

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/gzq?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password: gzq102938
      minIdle: 10
      maxActive: 20
      time-between-eviction-runs-millis: 60000
      validation-query: select 1 from dual
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    virtual-host: /
#    password: guest
#  mvc:
#    static-path-pattern: /static/**
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    encoding: utf-8
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        register: true
        root: /service
        enabled: true
  application:
    name: /ol-consumer

mybatis:
    mapperLocations: classpath:mapper/**/*Mapper.xml
    configLocation: classpath:mybatis-config.xml

logging:
  level:
    org.yu: debug
    org.springframework: warn